services:
    tdm_maps_module.app_settings:
        class: TdM\MapsModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
