services:
    # Event subscribers and listeners
    tdm_maps_module.entity_lifecycle_listener:
        class: TdM\MapsModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    tdm_maps_module.kernel_listener:
        class: TdM\MapsModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.installer_listener:
        class: TdM\MapsModule\Listener\InstallerListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.moduledispatch_listener:
        class: TdM\MapsModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.mailer_listener:
        class: TdM\MapsModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.theme_listener:
        class: TdM\MapsModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.userlogin_listener:
        class: TdM\MapsModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.userlogout_listener:
        class: TdM\MapsModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.user_listener:
        class: TdM\MapsModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@tdm_maps_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.userregistration_listener:
        class: TdM\MapsModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.users_listener:
        class: TdM\MapsModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.group_listener:
        class: TdM\MapsModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.thirdparty_listener:
        class: TdM\MapsModule\Listener\ThirdPartyListener
        arguments:
            - "@tdm_maps_module.workflow_helper"
        tags: ['kernel.event_subscriber']
    
    tdm_maps_module.workflow_events_listener:
        class: TdM\MapsModule\Listener\WorkflowEventsListener
        arguments:
            - "@zikula_permissions_module.api.permission"
            - "@tdm_maps_module.notification_helper"
        tags: ['kernel.event_subscriber']
    
