<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Form\Type;

use TdM\MapsModule\Form\Type\Base\AbstractMapType;

/**
 * Map editing form type implementation class.
 */
class MapType extends AbstractMapType
{
    // feel free to extend the map editing form type class here
}
