<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule;

use TdM\MapsModule\Base\AbstractAppSettings;

/**
 * Application settings class for handling module variables.
 */
class AppSettings extends AbstractAppSettings
{
    // feel free to add your own methods here
}
