<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule;

use TdM\MapsModule\Base\AbstractMapsEvents;

/**
 * Events definition implementation class.
 */
class MapsEvents extends AbstractMapsEvents
{
    // feel free to extend the events definition here
}
