<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Validator\Constraints;

use TdM\MapsModule\Validator\Constraints\Base\AbstractListEntry;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class ListEntry extends AbstractListEntry
{
    // here you can customise the constraint
}
