<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Event;

use TdM\MapsModule\Event\Base\AbstractFilterMapEvent;

/**
 * Event implementation class for filtering map processing.
 */
class FilterMapEvent extends AbstractFilterMapEvent
{
    // feel free to extend the event class here
}
