<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Block;

use TdM\MapsModule\Block\Base\AbstractModerationBlock;

/**
 * Moderation block implementation class.
 */
class ModerationBlock extends AbstractModerationBlock
{
    // feel free to extend the moderation block here
}
