<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Form\Handler\Map;

use TdM\MapsModule\Form\Handler\Map\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the map object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
	/**
     * Command event handler.
     *
     * This event handler is called when a command is issued by the user.
     *
     * @param array $args List of arguments
     *
     * @return mixed Redirect or false on errors
     */
    /*public function handleCommand(array $args = [])
    {
        $EstiloMapa = FormUtil::getPassedValue('EstiloMapa', isset($args['EstiloMapa']) ? $args['EstiloMapa'] : null, 'POST');
		print_r($EstiloMapa);die();
    }*/
}
