<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Entity\Factory;

use TdM\MapsModule\Entity\Factory\Base\AbstractEntityFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 */
class EntityFactory extends AbstractEntityFactory
{
    // feel free to customise the factory
}
