<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\DependencyInjection;

use TdM\MapsModule\DependencyInjection\Base\AbstractTdMMapsExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class TdMMapsExtension extends AbstractTdMMapsExtension
{
    // custom enhancements can go here
}
