<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\HookSubscriber;

use TdM\MapsModule\HookSubscriber\Base\AbstractMapFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class MapFormAwareHookSubscriber extends AbstractMapFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
