services:
    # Form field types
    
    tdm_maps_module.form.type.field.upload:
        class: TdM\MapsModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@tdm_maps_module.image_helper"
            - "@tdm_maps_module.upload_helper"
        tags: ['form.type']
