services:
    # Form types
    
    tdm_maps_module.form.type.mapquicknav:
        class: TdM\MapsModule\Form\Type\QuickNavigation\MapQuickNavType
        arguments:
            - "@translator.default"
            - "@tdm_maps_module.listentries_helper"
        tags: ['form.type']
    
    tdm_maps_module.form.handler.common:
        abstract: true
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@tdm_maps_module.entity_factory"
            - "@tdm_maps_module.controller_helper"
            - "@tdm_maps_module.model_helper"
            - "@tdm_maps_module.workflow_helper"
            - "@tdm_maps_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
    
    
    tdm_maps_module.form.handler.map:
        class: TdM\MapsModule\Form\Handler\Map\EditHandler
        parent: tdm_maps_module.form.handler.common
    
    tdm_maps_module.form.type.map:
        class: TdM\MapsModule\Form\Type\MapType
        arguments:
            - "@translator.default"
            - "@tdm_maps_module.entity_factory"
            - "@tdm_maps_module.listentries_helper"
        tags: ['form.type']
    
    tdm_maps_module.form.type.mapfinder:
        class: TdM\MapsModule\Form\Type\Finder\MapFinderType
        arguments:
            - "@translator.default"
        tags: ['form.type']
    
    tdm_maps_module.form.type.config:
        class: TdM\MapsModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@=service('zikula_extensions_module.api.variable').getAll('TdMMapsModule')"
            - "@zikula_groups_module.group_repository"
        tags: ['form.type']
