services:
    tdm_maps_module.hook_subscriber.filter_hooks.maps:
        class: TdM\MapsModule\HookSubscriber\MapFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.tdmmapsmodule.filter_hooks.maps' }

    tdm_maps_module.hook_subscriber.form_aware_hook.maps:
        class: TdM\MapsModule\HookSubscriber\MapFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.tdmmapsmodule.form_aware_hook.maps' }

    tdm_maps_module.hook_subscriber.ui_hooks.maps:
        class: TdM\MapsModule\HookSubscriber\MapUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.tdmmapsmodule.ui_hooks.maps' }

