services:
    tdm_maps_module.link_container:
        class: TdM\MapsModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@tdm_maps_module.controller_helper"
        tags: ['zikula.link_container']
