<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Helper;

use TdM\MapsModule\Helper\Base\AbstractSearchHelper;

/**
 * Search helper implementation class.
 */
class SearchHelper extends AbstractSearchHelper
{
    // feel free to extend the search helper here
}
