<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use TdM\MapsModule\Entity\MapEntity;

/**
 * Event base class for filtering map processing.
 */
class AbstractFilterMapEvent extends Event
{
    /**
     * @var MapEntity Reference to treated entity instance.
     */
    protected $map;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterMapEvent constructor.
     *
     * @param MapEntity $map Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(MapEntity $map, array $entityChangeSet = [])
    {
        $this->map = $map;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return MapEntity
     */
    public function getMap()
    {
        return $this->map;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
