<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Form\Type\Field;

use TdM\MapsModule\Form\Type\Field\Base\AbstractUploadType;

/**
 * Upload field type implementation class.
 */
class UploadType extends AbstractUploadType
{
    // feel free to add your customisation here
}
