<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.1.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Form\Type\QuickNavigation;

use TdM\MapsModule\Form\Type\QuickNavigation\Base\AbstractMapQuickNavType;

/**
 * Map quick navigation form type implementation class.
 */
class MapQuickNavType extends AbstractMapQuickNavType
{
    // feel free to extend the base form type class here
}
