<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Form\DataTransformer;

use TdM\MapsModule\Form\DataTransformer\Base\AbstractUploadFileTransformer;

/**
 * Upload file transformer implementation class.
 *
 * This data transformer treats uploaded files.
 */
class UploadFileTransformer extends AbstractUploadFileTransformer
{
    // feel free to add your customisation here
}
