<?php
/**
 * Maps.
 *
 * @copyright Krator (TdM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <torredemarfil@heroesofmightandmagic.es>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace TdM\MapsModule\Base;

use Doctrine\DBAL\Connection;
use RuntimeException;
use Zikula\Core\AbstractExtensionInstaller;

/**
 * Installer base class.
 */
abstract class AbstractMapsModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the TdMMapsModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $uploadHelper = new \TdM\MapsModule\Helper\UploadHelper(
                $container->get('translator.default'),
                $container->get('filesystem'),
                $container->get('session'),
                $container->get('logger'),
                $container->get('zikula_users_module.current_user'),
                $container->get('zikula_extensions_module.api.variable'),
                $container->getParameter('datadir')
            );
            $uploadHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $exception) {
            $this->addFlash('error', $exception->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'TdMMapsModule', 'user' => $userName, 'errorMessage' => $exception->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'TdMMapsModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('moderationGroupForMaps', 2);
        $this->setVar('mapEntriesPerPage', 10);
        $this->setVar('enableShrinkingForMapForeground', false);
        $this->setVar('shrinkWidthMapForeground', 800);
        $this->setVar('shrinkHeightMapForeground', 600);
        $this->setVar('thumbnailModeMapForeground', 'inset');
        $this->setVar('thumbnailWidthMapForegroundView', 32);
        $this->setVar('thumbnailHeightMapForegroundView', 24);
        $this->setVar('thumbnailWidthMapForegroundDisplay', 240);
        $this->setVar('thumbnailHeightMapForegroundDisplay', 180);
        $this->setVar('thumbnailWidthMapForegroundEdit', 240);
        $this->setVar('thumbnailHeightMapForegroundEdit', 180);
        $this->setVar('enableShrinkingForMapUnderground', false);
        $this->setVar('shrinkWidthMapUnderground', 800);
        $this->setVar('shrinkHeightMapUnderground', 600);
        $this->setVar('thumbnailModeMapUnderground', 'inset');
        $this->setVar('thumbnailWidthMapUndergroundView', 32);
        $this->setVar('thumbnailHeightMapUndergroundView', 24);
        $this->setVar('thumbnailWidthMapUndergroundDisplay', 240);
        $this->setVar('thumbnailHeightMapUndergroundDisplay', 180);
        $this->setVar('thumbnailWidthMapUndergroundEdit', 240);
        $this->setVar('thumbnailHeightMapUndergroundEdit', 180);
        $this->setVar('enabledFinderTypes', 'map');
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the TdMMapsModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $exception) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'TdMMapsModule', 'errorMessage' => $exception->getMessage()]);
    
                    return false;
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall TdMMapsModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'TdMMapsModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // remove all module vars
        $this->delVars();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/TdMMapsModule/';
        $this->addFlash('status', $this->__f('The upload directories at "%path%" can be removed manually.', ['%path%' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for TdMMapsModule.
     *
     * @return string[] List of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'TdM\MapsModule\Entity\MapEntity';
    
        return $classNames;
    }
}
